### ISSUE TITLE
multiprocess-safe logging

### ISSUE THREAD

**Issue by dbyron0** [fluent/serverengine#19]
From what I can tell, each worker process writes to the same log file.  Is that correct?

Am I also correct that it's possible for one process to 'step on' another?  Specifically, what's stopping one process from writing a log message while another one is in the middle of writing one?

I see a mutex in MultiprocessFileLogDevice in https://github.com/fluent/serverengine/blob/master/lib/serverengine/daemon_logger.rb, but that's only for ruby < 2.1 and only protects from simultaneous writes across threads, not processes, correct?

Thanks for your help.

-DB

**Comment by repeatedly** [comment]
> From what I can tell, each worker process writes to the same log file. Is that correct?

Correct.

> Specifically, what's stopping one process from writing a log message while another one is in the middle of writing one?

`write` system-call acquires a lock internally on typical cases.

> but that's only for ruby < 2.1 

Yes because Ruby 2.1's LogDevice is also multi-process safe since 2.1: https://github.com/ruby/ruby/pull/428

**Comment by dbyron0** [comment]
Thanks for the detailed info. This is very helpful.
